### ISSUE TITLE
about_classes

### ISSUE THREAD

**Issue by doguhanyeke** [sourabhv/python-koans-solutions#3]
you just commented the line.

self.assertEqual(<"Dog named 'Fido'">, fido.get_self())  # Not a string!

!!!

**Comment by sourabhv** [comment]
This was 5 years ago, I don't remember what I was doing 😛

**Comment by doguhanyeke** [comment]
bro, you are the first (and the only) one that offers solutions when googled. you have responsibilities to community ahahaa. Good work, hero!
